### ISSUE TITLE
commandargs reports only the first flag

### ISSUE THREAD

**Issue by filippog** [Dev25/mcrouter_exporter#1]
Hi,
thanks for mcrouter_exporter!

Looks like when parsing `commandargs` only the first option is reported because of whitespace splitting:

```
STAT commandargs --debug-fifo-root /var/lib/mcrouter/fifos [etc]
```

```
mcrouter_commandargs{commandargs="--debug-fifo-root"} 1
```

**Comment by Dev25** [comment]
Thanks for reporting, this will be fixed shortly by moving away from `strings.Split`  and to using `strings.SplitN` instead so it just splits the stat line into 3 components.

**Comment by Dev25** [comment]
Fixed in https://github.com/Dev25/mcrouter_exporter/commit/bb474c0b1cbb78965a2387390905a2bafd242225
