### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by davidkarlsen** [Dev25/mcrouter_exporter#12]

**Comment by Dev25** [comment]
Happy to review PRs as they come in, is there something specific you wanted in this exporter?

The functionality this exporter provides is fairly minimal (scrape/export prometheus metrics) which currently works well so there isn't that much ongoing development required.

**Comment by davidkarlsen** [comment]
Hi - not missing any functionality - but it would be nice with some final tags and according versions on dockerhub or quay. Then I could brush up the helm-chart and add this exporter to it.

**Comment by Dev25** [comment]
Right i got you, i have been meaning to update the CI to generate branch tagged images `master-$SHORT_SHA` along with git tagged releases. Let me do that and cut a release and i'll ping you when done.

**Comment by Dev25** [comment]
@davidkarlsen I've cut a `0.1.0` release along with a corresponding docker tag.

https://quay.io/repository/dev25/mcrouter_exporter?tab=tags
