### ISSUE TITLE
Add ability to allow or disable specific metrics

### ISSUE THREAD

**Issue by blkperl** [Dev25/mcrouter_exporter#22]
Would there be any interest in new configuration that allows the users to choose which metrics are sent by the exporter? I can submit a pull request.

In my use case we have thousands of pods running mcrouter and we have exceeded our quota for metrics so we want to restrict the metrics sent to the ones that are needed.

**Comment by Dev25** [comment]
Yeah that sounds reasonable, happy to review a PR. 
Had any early thoughts on how it will be configured, cli flags only or config file?

**Comment by blkperl** [comment]
I've since learned that I can filter prometheus metrics and use `action: drop` to remove metrics that we are not interested in. Thanks for the response though.
