### ISSUE TITLE
mcrouter-exporter does not work anymore if mcrouter is restarted

### ISSUE THREAD

**Issue by elukey** [Dev25/mcrouter_exporter#4]
Hi!

I noticed that if mcrouter is restarted, then the exporter does not work anymore (this is from journald's logs):

```
level=error msg="Failed to collect stats from mcrouter: EOF" source="main.go:313"
```

It would be great if EOF was recognized (maybe in getStats or Collect) to re-establish the tcp connection to mcrouter. If you don't have time I can try to submit a pull request!

Thanks in advance,

Luca

**Comment by elukey** [comment]
I also tried to start the exporter alone, and a call to /metrics leads to a segfault:

```
vagrant@stretch:~/mcrouter_exporter$ ./mcrouter_exporter
INFO[0000] Starting mcrouter_exporter (version=, branch=, revision=)  source="main.go:454"
INFO[0000] Build context (go=go1.7.4, user=, date=)      source="main.go:455"
INFO[0000] Starting HTTP server on :9151                 source="main.go:468"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x46d64b]

goroutine 29 [running]:
panic(0x8042a0, 0xc42000c0c0)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
fmt.Fprintf(0x0, 0x0, 0x87c34e, 0xb, 0x0, 0x0, 0x0, 0x29108, 0x6fc8000, 0x44f)
        /usr/lib/go-1.7/src/fmt/print.go:182 +0x7b
main.getStats(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vagrant/mcrouter_exporter/main.go:411 +0xf8
main.(*Exporter).Collect(0xc4200830e0, 0xc420054ba0)
        /home/vagrant/mcrouter_exporter/main.go:310 +0x52
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /home/vagrant/src/github.com/prometheus/client_golang/prometheus/registry.go:430 +0x113
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/vagrant/src/github.com/prometheus/client_golang/prometheus/registry.go:441 +0x649
```

So probably the TCP connection should be created elsewhere and test that it doesn't return any error.

**Comment by elukey** [comment]
I created a pull request that should solve these issues, I've tested it and it seems working. If you like the idea I can also add tests if necessary, otherwise I'll wait for a new version of the exporter :)

**Comment by Dev25** [comment]
Fix worked for me locally on both issues raised, thanks for the PR.

**Comment by elukey** [comment]
Thanks for the review! The last thing that I want to verify is that the "old" connection ended up in EOF does not leak for some reason. There shouldn't be any need to explicitly close the connection/socket before opening a new one but better safe than sorry :)

**Comment by elukey** [comment]
So I added a little change to the code, in this last commit in case of io.EOF the socket is explicitly closed just to be sure, hope it is fine to not use pointers for the conn (but I am possibly doing something wrong, lemme know in case). The test cases are a bit tricky, do you have already something in mind? Thanks :)

**Comment by elukey** [comment]
I had a chat with @filippog (a colleague of mine) and some interesting point came up, writing them down to discuss them with whoever is interested:
1) a more simple logic, like create a socket each time that a GET /metrics request lands, it is definitely simpler and it makes the code way more readable.
2) the Exporter struct, in theory global, holds the conn handle and can be modifiable by multiple collect calls happening at the same time. This shouldn't be a big issue but surely worth to consider.

About 1), the only downside would be that we'd leave a connection in TIME_WAIT after each GET /metrics. This shouldn't be an issue on systems like Linux in which tw_reuse allows to reuse a socket in time wait after few seconds. The overhead of establishing a tcp connection in localhost is minimal in my opinion..

@Dev25 what do you think about moving to a simpler solution like:

```
func (e *Exporter) Collect(ch chan<- prometheus.Metric) {

	conn, err := net.DialTimeout("tcp", e.server, e.timeout)
	if conn == nil {
		ch <- prometheus.MustNewConstMetric(e.up, prometheus.GaugeValue, 0)
		log.Errorf("Failed to collect stats from mcrouter.")
		return
	}
	s, err := getStats(conn)

	if err != nil {
		ch <- prometheus.MustNewConstMetric(e.up, prometheus.GaugeValue, 0)
		log.Errorf("Failed to collect stats from mcrouter: %s", err)
		return
	}
	conn.Close()
```

**Comment by Dev25** [comment]
That sounds fine to me @elukey 

In fact looking at memcached_exporter, that too ended up moving to creating a new client inside `Collect` and just storing the server address in `Exporter`

https://github.com/prometheus/memcached_exporter/pull/21/files

**Comment by elukey** [comment]
Thanks! Updated the pull request and tested, looks good to me so far. As expected I am now seeing a bit more sockets in TIME_WAIT after each collect, but it is not a big deal. Added some info about it in the commit msg. Let me know if the change is ok!

**Comment by elukey** [comment]
@Dev25 Any comment? :)

**Comment by Dev25** [comment]
Sorry for the delay, PR has been merged to master.
