### ISSUE TITLE
Consider adding 'stats servers' to the list of metrics

### ISSUE THREAD

**Issue by elukey** [Dev25/mcrouter_exporter#9]
Hi!

I am wondering if it would be ok to consider adding an optional parameter to the exporter to emit metrics related to the content of `stats servers`. In my case, this is an example of part of the output:

```
STAT 10.64.0.81:11211:ascii:plain:notcompressed-1000 avg_latency_us:344.766 pending_reqs:0 inflight_reqs:0 avg_retrans_ratio:0 max_retrans_ratio:0 min_retrans_ratio:0 up:5; deleted:108046 touched:869669 found:1951422718 notfound:66660413 notstored:1825893 stored:51096164 exists:19914 timeout:183 remote_error:70
```

These metrics are way more precise than the aggregated ones, especially when only one or two shards are misbehaving (since outliers may not be seen because smoothened over by the other values). It would be great to have something like:

```
mcrouter_server_avg_latency_us{shard="10.64.0.81:11211:ascii:plain:notcompressed-1000"} 344.766
mcrouter_server_timeouts{shard="10.64.0.81:11211:ascii:plain:notcompressed-1000"} 344.766
etc..
```

This extra set of metrics could be optional, enabled via argument if needed (to avoid adding the extra call to mcrouter if not needed). What do you think? I am available to provide a pull request in case!

**Comment by elukey** [comment]
@Dev25 any opinion? :)

**Comment by Dev25** [comment]
That sound fine, if you send over a PR I can take a look.

I think it should be fine to have this exported by default, possibly with a opt out flag rather then opt in but I have no strong opinion on that.

**Comment by elukey** [comment]
No strong opinion either, I would just add a parameter to allow people to not use this feature if they feel so when upgrading :)

I'll try to send a PR during the next days!
